services:
  task-manager-db:
    restart: on-failure
    image: postgres
    container_name: task-manager-db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - taskManagerDB:/var/lib/postgresql/data
    networks:
      - task-manager-network

  task-manager-backend:
    build:
      context: ./backend
    container_name: task-manager-backend
    command: npm run install_migrate_seed_and_start
    volumes:
      - user_uploads:/app/user_uploads/
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      PORT: ${BACKEND_PORT}
      DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@task-manager-db:5432/${POSTGRES_DB}
    depends_on:
      - task-manager-db
    networks:
      - task-manager-network
  
volumes:
  user_uploads:
  taskManagerDB:

networks:
  task-manager-network:
