services:
  task_manager_db:
    restart: on-failure
    image: postgres
    container_name: task_manager_db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - task_manager:/var/lib/postgresql/data
    networks:
      - task-manager-network

  task_manager_backend:
    build:
      context: ./backend
    container_name: task_manager_backend
    command: npm run migrate_seed_and_start
    volumes:
      - user_uploads:/app/user_uploads/
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      PORT: ${BACKEND_PORT}
      DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@task_manager_db:5432/${POSTGRES_DB}
    depends_on:
      - task_manager_db
    networks:
      - task-manager-network

volumes:
  user_uploads:
  task_manager:

networks:
  task-manager-network:
