const PROJECTS_AMOUNT = 250;
const USERS_AMOUNT = 200;
const USER_PROJECTS_AMOUNT = 500;
const MAX_MANAGER_INDEX = 20;

module.exports = {
	PROJECTS_AMOUNT,
	USERS_AMOUNT,
	USER_PROJECTS_AMOUNT,
	MAX_MANAGER_INDEX
};
